"""Minimal closed-loop research governor."""

from .adversarial import (
    AdversarialOutcome,
    AdversarialScienceLoop,
    Candidate,
    CandidateAssessment,
    CandidateStatus,
    EvidenceUpdate,
    FalsifyingExperiment,
    NoveltyIndex,
    RedTeamReview,
    RoleAssignment,
    ScientificRole,
)
from .governor import GovernorConfig, MinimalResearchGovernor
from .models import CycleDecision, CycleOutcome, ExperimentProposal
from .selection import InformationGainSelector, RandomSelector
from .topology import (
    AdaptiveResourceTopology,
    Allocation,
    AllocationStrategy,
    FixedResourcePolicy,
    PerformanceObservation,
    PolicyComparison,
    ResourceStrategyProfile,
    StrategyCheckpoint,
    TopologyAction,
    TopologyActionKind,
    Workload,
    evaluate_policy,
    paired_policy_comparison,
)

__all__ = [
    "AdversarialOutcome",
    "AdversarialScienceLoop",
    "AdaptiveResourceTopology",
    "Allocation",
    "AllocationStrategy",
    "Candidate",
    "CandidateAssessment",
    "CandidateStatus",
    "CycleDecision",
    "CycleOutcome",
    "ExperimentProposal",
    "EvidenceUpdate",
    "FalsifyingExperiment",
    "FixedResourcePolicy",
    "GovernorConfig",
    "InformationGainSelector",
    "MinimalResearchGovernor",
    "NoveltyIndex",
    "PerformanceObservation",
    "PolicyComparison",
    "RandomSelector",
    "RedTeamReview",
    "RoleAssignment",
    "ScientificRole",
    "ResourceStrategyProfile",
    "StrategyCheckpoint",
    "TopologyAction",
    "TopologyActionKind",
    "Workload",
    "evaluate_policy",
    "paired_policy_comparison",
]
